### ISSUE TITLE
Unicode Decode Error when running the LRS2 data preparation

### ISSUE THREAD

**Issue by gak97** [mpc001/auto_avsr#1]
Thank you for providing the training code for the Auto AVSR.

I am facing an issue when trying to run the `preprocess_lrs2lrs3.py` file using the LRS2 dataset. I am seeing the below error:

Traceback (most recent call last):
  File "preprocess_lrs2lrs3.py", line 77, in <module>
    text_transform = TextTransform()
  File "A:\Projects\auto_avsr\preparation\transforms.py", line 152, in __init__
    units = open(dict_path).read().splitlines()
  File "C:\Users\Girish\anaconda3\envs\autoavsr\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 4416: character maps to <undefined>

Any help to resolve this would be greatly appreciated!

**Comment by gak97** [comment]
Hi @mpc001, that resolved the error! Closing this issue here.
