### ISSUE TITLE
Running Demo gets ModuleNotFoundError: No module named 'six' 

### ISSUE THREAD

**Issue by M1ndBlast** [mpc001/auto_avsr#16]
I've tried to run demo with a video for vsr executing the next line:
```
(TT) PS D:\auto_avsr> python demo.py data.modality='audio' pretrained_model_path='.\asr_trlrs3vox2_base.pth' file_path='.\avsr_english_1.mp4'
```
but i got the next error

```
Traceback (most recent call last):
  File "demo.py", line 7, in <module>
    from lightning import ModelModule
  File "D:\auto_avsr\lightning.py", line 7, in <module>
    from espnet.nets.batch_beam_search import BatchBeamSearch
  File "D:\auto_avsr\espnet\nets\batch_beam_search.py", line 8, in <module>
    from espnet.nets.beam_search import BeamSearch, Hypothesis
  File "D:\auto_avsr\espnet\nets\beam_search.py", line 9, in <module>
    from espnet.nets.e2e_asr_common import end_detect
  File "D:\auto_avsr\espnet\nets\e2e_asr_common.py", line 16, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

I already execute step by step to setup enviroment, and already install c++ requirements but still get the same error

Conda enviroment
Python 3.8.18
Windows 11 w/ powershell

**Comment by mpc001** [comment]
Hi @M1ndBlast, can you please install that package `pip install six`?

**Comment by M1ndBlast** [comment]
I installed six

```
(TT) PS C:\Users\peduz> pip install six
Collecting six
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
DEPRECATION: pytorch-lightning 1.5.10 has a non-standard dependency specifier torch>=1.7.*. pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pytorch-lightning or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
Installing collected packages: six
Successfully installed six-1.16.0
```

And I get new missing module "ibug"
```
(TT) PS D:\auto_avsr> python demo.py data.modality='video' pretrained_model_path='.\asr_trlrs3vox2_base.pth' file_path='.\avsr_english_1.mp4'
Error executing job with overrides: ['data.modality=video', 'pretrained_model_path=.\\asr_trlrs3vox2_base.pth', 'file_path=.\\avsr_english_1.mp4']
Traceback (most recent call last):
  File "demo.py", line 77, in main
    pipeline = InferencePipeline(cfg)
  File "demo.py", line 24, in __init__
    from preparation.detectors.retinaface.detector import LandmarksDetector
  File "D:\auto_avsr\preparation\detectors\retinaface\detector.py", line 9, in <module>
    from ibug.face_alignment import FANPredictor
ModuleNotFoundError: No module named 'ibug'

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
```

and now I can't install ibug

```
(TT) PS D:\auto_avsr> pip install ibug
ERROR: Ignored the following versions that require a different python version: 0.0.3 Requires-Python >=3.9; 0.0.4 Requires-Python >=3.9; 0.0.5 Requires-Python >=3.9; 0.0.7 Requires-Python >=3.9; 0.0.9 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement ibug (from versions: none)
ERROR: No matching distribution found for ibug
```

**Comment by mpc001** [comment]
Hi @M1ndBlast, can you please install the face tracker and face alignment libraries by following PR #17?

**Comment by M1ndBlast** [comment]
Done. Sorry for take too time (evaluation period stuff)

I installed it with Option 1. Tried command again and i get next error:
![image](https://github.com/mpc001/auto_avsr/assets/39204641/246ca6f9-ba95-4c2c-9880-37d257689783)

CUDA is required?

**Comment by liu33333** [comment]
需要cuda的，前提是你的pytorch版本正确
