### ISSUE TITLE
 cannot import name 'eval_env' from 'torchaudio._internal.module_utils' 

### ISSUE THREAD

**Issue by YuQing2000** [mpc001/auto_avsr#24]
When I run:
`python train.py exp_dir=D:/pycharmProject/auto_avsr-main/auto_avsr-main/checkpoints exp_name=exp1 data.modality=video data.dataset.root_dir=D:/BaiduNetdiskDownload/pre `

I got this error:
`Traceback (most recent call last):
  File "train.py", line 10, in <module>
    from datamodule.data_module import DataModule
  File "D:\pycharmProject\auto_avsr-main\auto_avsr-main\datamodule\data_module.py", line 6, in <module>
    from .av_dataset import AVDataset
  File "D:\pycharmProject\auto_avsr-main\auto_avsr-main\datamodule\av_dataset.py", line 4, in <module>
    import torchaudio
  File "D:\anaconda3\envs\auto_avsr\lib\site-packages\torchaudio\__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "D:\anaconda3\envs\auto_avsr\lib\site-packages\torchaudio\_extension\__init__.py", line 5, in <module>
    from torchaudio._internal.module_utils import eval_env, fail_with_message, is_module_available, no_op
ImportError: cannot import name 'eval_env' from 'torchaudio._internal.module_utils' (D:\anaconda3\envs\auto_avsr\lib\site-packages\torchaudio\_internal\module_utils.py)
`

**Comment by mpc001** [comment]
Hi @YuQing2000, it seems that the `eval_env` function or component might not be available in the version of `torchaudio` you are using. Can you please consider re-installing your `torchaudio` installation?

**Comment by AlisonDexter** [comment]
Hello, Have you solved the problem? I just got this error, my envirnment is torch-1.13.0,python-3.10
